name: build/publish dev image

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: check out code
            uses: actions/checkout@v4

          - name: set up qemu/buildx
            uses: docker/setup-buildx-action@v3

          - name: log into ghcr
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

          - name: build and push image
            uses: docker/build-push-action
            with:
                context: .
                file: .devcontainer/dev-base.dockerfile
                push: true
                tags: |
                    ghcr.io/${{ github.repository_owner }}/dsptool-dev:latest
                    ghcr.io/${{ github.repository_owner }}/dsptool-dev:${{ github.sha }}